image: docker:git
services:
- docker:dind

stages:
- test
- build
- deploy

variables:
  DOCKER_DRIVER: overlay
  MASTER_CLIENT_IMAGE: registry.rainbowcrown.com:7443/root/simpleeditor:latest
  MASTER_CLIENT_PATH: ./
  MASTER_CLIENT_DOCKERFILE: ./Dockerfile
  DEVEL_CLIENT_IMAGE: registry.rainbowcrown.com:7443/root/simpleeditor:next
  DEVEL_CLIENT_PATH: ./
  DEVEL_CLIENT_DOCKERFILE: ./Dockerfile

## FEATURE STEPS
lint_develop:
  stage: test
  image: node:slim
  script:
    - npm install standard --global
    - npm install -g snazzy
    - standard --verbose | snazzy
  only:
    - /^feature/.*$/
  allow_failure: true

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.rainbowcrown.com:7443
    - docker build -f $MASTER_CLIENT_DOCKERFILE -t $MASTER_CLIENT_IMAGE $MASTER_CLIENT_PATH
    - docker push $MASTER_CLIENT_IMAGE
  only:
    - master

build_devel:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.rainbowcrown.com:7443
    - docker build -f $DEVEL_CLIENT_DOCKERFILE -t $DEVEL_CLIENT_IMAGE $DEVEL_CLIENT_PATH
    - docker push $DEVEL_CLIENT_IMAGE
  only:
    - develop
